### ISSUE TITLE
Empty BIC code added => Invalid 

### ISSUE THREAD

**Issue by stefanve** [mgmco/sepa-xml#14]
It is allowed, according to the specs and in practice, to leave out the BIC completely. The sepa-xml does however add an empty BIC block that makes the document invalid (if it is present it cannot be empty)

`
<CdtrAgt>
        <FinInstnId>
           <BIC></BIC>
       </FinInstnId>
</CdtrAgt>
`

When I delete that part from the XML created, it validates and the bank accepts it

**Comment by mtimofiiv** [comment]
Good catch! I'll take care of this this weekend.

**Comment by stefanve** [comment]
Any news about this?

**Comment by mtimofiiv** [comment]
I'm assuming you mean for the payee, right, not to the account where it's going? Because we already check if the BIC could be found for the account we're paying:

https://github.com/mgmco/sepa-xml/blob/master/formats/pain.001.001.03.hbs#L55

But indeed I will add it for the payee, and it also looks to be lacking from the `pain.001.001.02` format for both of those spots.

**Comment by mtimofiiv** [comment]
Ok, updated, and the package has been bumped as well on NPM.
